language: bash
services: docker
before_install:
  - cd 17RestWithSpringBootUdemyDocker/
  - echo "We are in the docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push guilhermegarcia/mysql-rest-with-spring-boot-udemy;
    docker push guilhermegarcia/rest-with-spring-boot-udemy;
  on:
    branch: master
  email: false
